jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Install Poetry'
        run: 'pipx install poetry'
      - name: 'Set up Python'
        uses: 'actions/setup-python@v5'
        with:
          cache: 'poetry'
          python-version: '3.13'
      - name: 'Install dependencies (Poetry)'
        run: 'poetry install --with=dev --no-root'
      - name: 'Install dependencies (Yarn)'
        run: 'yarn'
      - name: 'Lint with mypy'
        run: 'yarn mypy .'
      - name: 'Lint with Ruff'
        run: 'yarn ruff .'
      - name: 'Check formatting'
        run: 'yarn check-formatting'
      - name: 'Check spelling'
        run: 'yarn check-spelling'
name: 'QA'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: read
